# Generated by Django 5.1.6 on 2025-03-03 20:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_worker_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasktype',
            options={'verbose_name': 'Task Type', 'verbose_name_plural': 'Task Types'},
        ),
        migrations.AlterField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
